import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 0;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Sum of money is $: \{root.counter}";
        }
        Button {
            text: "Add 1 dollar";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
